enum OpCode {
  SVTCA0,
  SVTCA1,
  SPVTCA0,
  SPVTCA1,
  SFVTCA0,
  SFVTCA1,
  SPVTL0,
  SPVTL1,
  SFVTL0,
  SFVTL1,
  SPVFS,
  SFVFS,
  GPV,
  GFV,
  SFVTPV,
  ISECT,
  SRP0,
  SRP1,
  SRP2,
  SZP0,
  SZP1,
  SZP2,
  SZPS,
  SLOOP,
  RTG,
  RTHG,
  SMD,
  ELSE,
  JMPR,
  SCVTCI,
  SSWCI,
  SSW,
  DUP,
  POP,
  CLEAR,
  SWAP,
  DEPTH,
  CINDEX,
  MINDEX,
  ALIGNPTS,
  /* unused: 0x28 */
  UTP, // = 0x29
  LOOPCALL,
  CALL,
  FDEF,
  ENDF,
  MDAP0,
  MDAP1,
  IUP0,
  IUP1,
  SHP0,
  SHP1,
  SHC0,
  SHC1,
  SHZ0,
  SHZ1,
  SHPIX,
  IP,
  MSIRP0,
  MSIRP1,
  ALIGNRP,
  RTDG,
  MIAP0,
  MIAP1,
  NPUSHB,
  NPUSHW,
  WS,
  RS,
  WCVTP,
  RCVT,
  GC0,
  GC1,
  SCFS,
  MD0,
  MD1,
  MPPEM,
  MPS,
  FLIPON,
  FLIPOFF,
  DEBUG,
  LT,
  LTEQ,
  GT,
  GTEQ,
  EQ,
  NEQ,
  ODD,
  EVEN,
  IF,
  EIF,
  AND,
  OR,
  NOT,
  DELTAP1,
  SDB,
  SDS,
  ADD,
  SUB,
  DIV,
  MUL,
  ABS,
  NEG,
  FLOOR,
  CEILING,
  ROUND0,
  ROUND1,
  ROUND2,
  ROUND3,
  NROUND0,
  NROUND1,
  NROUND2,
  NROUND3,
  WCVTF,
  DELTAP2,
  DELTAP3,
  DELTAC1,
  DELTAC2,
  DELTAC3,
  SROUND,
  S45ROUND,
  JROT,
  JROF,
  ROFF,
  /* unused: 0x7B */
  RUTG, // = 0x7C
  RDTG,
  SANGW,
  AA,
  FLIPPT,
  FLIPRGON,
  FLIPRGOFF,
  /* unused: 0x83 - 0x84 */
  SCANCTRL, // = 0x85
  SDPVTL0,
  SDPVTL1,
  GETINFO,
  IDEF,
  ROLL,
  MAX,
  MIN,
  SCANTYPE,
  INSTCTRL,
  /* unused: 0x8F - 0xAF */
  PUSHB1, // = 0xB0
  PUSHB2,
  PUSHB3,
  PUSHB4,
  PUSHB5,
  PUSHB6,
  PUSHB7,
  PUSHB8,
  PUSHW1,
  PUSHW2,
  PUSHW3,
  PUSHW4,
  PUSHW5,
  PUSHW6,
  PUSHW7,
  PUSHW8,
  MDRP, // range of 32 values, 0xC0 - 0xDF,
  MIRP // range of 32 values, 0xE0 - 0xFF
}

extension OpCodeExtension on OpCode {
  static OpCode fromInt(int value) {
    if (value <= 0x28) return OpCode.values[value];
    if (value == 0x29) return OpCode.UTP;
    if (value <= 0x7A) return OpCode.values[value - 0x29 + OpCode.UTP.index];
    if (value == 0x7C) return OpCode.RUTG;
    if (value <= 0x82) return OpCode.values[value - 0x7C + OpCode.RUTG.index];
    if (value == 0x85) return OpCode.SCANCTRL;
    if (value <= 0x8E) return OpCode.values[value - 0x85 + OpCode.SCANCTRL.index];
    if (value >= 0xB0 && value <= 0xB7) return OpCode.values[value - 0xB0 + OpCode.PUSHB1.index];
    if (value >= 0xB8 && value <= 0xBF) return OpCode.values[value - 0xB8 + OpCode.PUSHW1.index];
    if (value >= 0xC0 && value <= 0xDF) return OpCode.MDRP;
    if (value >= 0xE0 && value <= 0xFF) return OpCode.MIRP;
    
    throw Exception('Unknown OpCode: $value');
  }
  
  int get value {
    // This is a bit tedious to implement in reverse, but we might not need it.
    // The interpreter reads bytes and converts to OpCode.
    return 0; 
  }
}
